services:
  auth:
    build: ./
    container_name: kelk_auth_container
    ports:
      - "${AUTH_PORT:-5000}:${AUTH_FORWARD_PORT:-5000}"
    volumes:
      - ./:/app

    networks:
      - kelk_network

  db:
    container_name: kelk_db_container
    image: postgres:17-alpine
    env_file:
      - .env
    restart: always

    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

    ports:
      - "${DB_PORT:-5432}:${DB_FORWARD_PORT:-5432}"

    volumes:
      - "./src/db/data:/var/lib/postgresql/data"

    networks:
      - kelk_network

networks:
  kelk_network:
    driver: bridge
