services:
  auth:
    container_name: kelk-auth-app-container
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER:-postgresql}:${DATABASE_PASSWORD:-password}@${DATABASE_HOST:-db}:${DATABASE_PORT:-5432}/${DATABASE_DB}?schema=public
    ports:
      - '${APP_PORT:-3000}:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
    networks:
      - kelk-network
    command: >
      sh -c "if [ \"$NODE_ENV\" = 'production' ]; then npm run build; npm run start:prod; else npm run start:dev; fi;"

  db:
    container_name: kelk-auth-db-container
    image: postgres:17-alpine
    env_file:
      - .env
    restart: always
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - kelk-network

  redis:
    container_name: kelk-auth-redis-container
    image: redis:7-alpine
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - ./redisdata:/data
    networks:
      - kelk-network

    command:
      [
        'redis-server',
        '--save',
        '60',
        '1',
        '--loglevel',
        'warning',
        '--requirepass',
        '${REDIS_PASSWORD}',
      ]

networks:
  kelk-network:
    driver: bridge
