name: Build Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened # Запуск при открытии PR
      - reopened # Запуск при повторном открытии PR
      - closed

jobs:
  build:
    runs-on: ubuntu-latest # Виртуальная машина для выполнения пайплайна

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Клонирование репозитория

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Укажите версию Node.js

      - name: run install
        run: npm install

      - name: Build project
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run install
        run: npm install

      - name: Run tests
        run: npm run test:exit

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test] # Деплой выполняется только после успешного выполнения build и test
    if: github.event.pull_request.state == 'closed' && github.event.pull_request.merged == true && (github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.base_ref == 'main')) # Выполняется только при пуше или pull request в ветку main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Deploy code to server
        run: |
          echo "Начинаем деплой..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            cd /www/wwwroot/kelk.imugor.ru/kelk-auth-service
            git pull origin main
            docker compose down
            docker compose up -d
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
