name: Deploy Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code to server
        run: |
          echo "Начинаем деплой..."
          echo ${{ secrets.SERVER_USER }}
          ssh -T -v -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            cd /www/wwwroot/kelk.imugor.ru/kelk-auth-service
            git pull origin main
            docker compose down
            docker compose up -d
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
